/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAkinatorRouteImport } from './routes/api/akinator'
import { Route as ApiAnuQrngRouteImport } from './routes/api/anu-qrng'
import { Route as ApiWritingIqRouteImport } from './routes/api/writing-iq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAkinatorRoute = ApiAkinatorRouteImport.update({
  id: '/api/akinator',
  path: '/api/akinator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnuQrngRoute = ApiAnuQrngRouteImport.update({
  id: '/api/anu-qrng',
  path: '/api/anu-qrng',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWritingIqRoute = ApiWritingIqRouteImport.update({
  id: '/api/writing-iq',
  path: '/api/writing-iq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/akinator': typeof ApiAkinatorRoute
  '/api/anu-qrng': typeof ApiAnuQrngRoute
  '/api/writing-iq': typeof ApiWritingIqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/akinator': typeof ApiAkinatorRoute
  '/api/anu-qrng': typeof ApiAnuQrngRoute
  '/api/writing-iq': typeof ApiWritingIqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/akinator': typeof ApiAkinatorRoute
  '/api/anu-qrng': typeof ApiAnuQrngRoute
  '/api/writing-iq': typeof ApiWritingIqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/akinator' | '/api/anu-qrng' | '/api/writing-iq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/akinator' | '/api/anu-qrng' | '/api/writing-iq'
  id: '__root__' | '/' | '/api/akinator' | '/api/anu-qrng' | '/api/writing-iq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAkinatorRoute: typeof ApiAkinatorRoute
  ApiAnuQrngRoute: typeof ApiAnuQrngRoute
  ApiWritingIqRoute: typeof ApiWritingIqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/akinator': {
      id: '/api/akinator'
      path: '/api/akinator'
      fullPath: '/api/akinator'
      preLoaderRoute: typeof ApiAkinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anu-qrng': {
      id: '/api/anu-qrng'
      path: '/api/anu-qrng'
      fullPath: '/api/anu-qrng'
      preLoaderRoute: typeof ApiAnuQrngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/writing-iq': {
      id: '/api/writing-iq'
      path: '/api/writing-iq'
      fullPath: '/api/writing-iq'
      preLoaderRoute: typeof ApiWritingIqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAkinatorRoute: ApiAkinatorRoute,
  ApiAnuQrngRoute: ApiAnuQrngRoute,
  ApiWritingIqRoute: ApiWritingIqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
